Optimistic-locking dataset write with etag
zowe/zowe-common-c pull request #249
Opened 2021-10-05 22:19 UTC by 1000TurquoisePogs

Builds upon https://github.com/zowe/zowe-common-c/pull/247 to implement writing.
Details in https://github.com/zowe/zss/pull/355

2021-10-06 05:02 UTC, lchudinov requested changes
Please see my comments on memory management.

2021-10-06 14:11 UTC, adityadr-joy commented on c/datasetjson.c
> +  char *eTag;
eTag pointer can be initialized to NULL

2021-10-06 14:28 UTC, adityadr-joy commented on c/datasetjson.c
> +    int len = digest.hashLength;
len is unused variable

2021-10-06 14:37 UTC, adityadr-joy commented on c/datasetjson.c
> +    memset(eTag, '\0', eTagLength);
memset length should be eTagLength+1

2021-10-06 14:38 UTC, adityadr-joy commented on c/datasetjson.c
> +    int len = digest.hashLength;
len is unused variable

2021-10-07 10:25 UTC, lchudinov approved these changes
It looks good to me. Please only add a NULL check for `lastEtag`

2021-10-07 19:29 UTC, merged