Created functionality for creating dataset members
zowe/zowe-common-c pull request #68
Opened 2019-07-30 18:46 UTC by chcaron01

Signed-off-by: Charlie Caron <ccaron@rocketsoftware.com>

2019-07-30 18:53 UTC, chcaron01 commented
@jordanfilteau1995

2019-08-01 18:45 UTC, jordanfilteau1995 requested changes

2019-08-01 18:45 UTC, jordanfilteau1995 commented on c/datasetjson.c
> +      int overwrite = !strcmp(overwriteParam, "true") ? TRUE : FALSE;
Do a string upper case and then compare against "TRUE".

!strcmp(overwriteParam, "TRUE") ? TRUE : FALSE;

2019-08-01 18:45 UTC, jordanfilteau1995 commented on c/datasetjson.c
> +      snprintf(fullPath, DATASET_MEMBER_MAXLEN + 1, "//'%s(%s)'", dsName, memName);
You will go out of bounds. You need space for the null terminator after snprintf. It should be this.

snprintf(fullPath, DATASET_MEMBER_MAXLEN, "//'%s(%s)'", dsName, memName);

2019-08-01 18:45 UTC, jordanfilteau1995 commented on c/datasetjson.c
> +      FILE* memberExists = fopen(fullPath,"r");
This whole chunk could be better if it was like the following. This isn't tested, it's just a rough outline.

      bool datasetExists = FALSE;
      FILE* datasetMember = fopen(fullPath,"r");
      if (memberExists) {
        datasetExists = TRUE;
      }
      
      int returnCode = fclose()
      if (returnCode != 0) {
        respondWithJsonError();
        return;
      }
      
      if (datasetExists) {
        if (!overwrite) {
          respondWithJsonError();
          return;     
        }
        else {
          createNewDatasetMember(); /* fopen(), fclose() */
        }
      }
      else {
        createNewDatasetMember(); /* fopen(), fclose() */
      }
      
      static int createNewDatasetMember() {
        int returnCode = 0;
        
        returnCode = fopen();
        if (returnCode != 0) {
          zowelog();
          return returnCode;
        }
        
        returnCode = fclose();
        if (returnCode != 0) {
          zowelog();
          return returnCode;
        }
        
        return returnCode;
      }

2019-08-01 18:45 UTC, jordanfilteau1995 commented on c/datasetjson.c
> +      snprintf(fullPath, DATASET_MEMBER_MAXLEN + 1, "//'%s(%s)'", dsName, memName);
You will go out of bounds on snprintf. Refer to comment above.

2019-08-02 19:31 UTC, jordanfilteau1995 approved these changes

2019-08-02 19:32 UTC, jordanfilteau1995 commented
DO NOT MERGE until merge conflicts are resolved in https://github.com/zowe/zss/pull/62

2019-08-08 15:22 UTC, ifakhrutdinov requested changes

2019-08-08 15:22 UTC, ifakhrutdinov commented on c/datasetjson.c
> +  memcpy(dsn.value, datasetName, DATASET_NAME_LEN);
A dataset name is not necessarily ```DATASET_NAME_LEN``` bytes. This may 0C4. And for DSCB it probably needs to be space padded.

2019-08-08 15:22 UTC, ifakhrutdinov commented on c/datasetjson.c
> +    respondWithJsonError(response, "Error decoding dataset", 400, "Bad Request");
Can you return from here early and not have a huge ```else```?

2019-08-08 15:22 UTC, ifakhrutdinov commented on c/datasetjson.c
> +    if (!isPartionedDataset(dscb)) {
Same here. Just check and return in case of an error.

2019-08-08 15:22 UTC, ifakhrutdinov commented on c/datasetjson.c
> +void newDatasetMember(HttpResponse* response, char* datasetPath, char* memberName) {
Why not follow the same convention as the rest of the function, i.e. require a full path? Please also do all the validation and checks (whether the dataset is on an offline volume), that's done in https://github.com/zowe/zowe-common-c/blob/staging/c/datasetjson.c#L832

2026-03-10 12:25 UTC, closed without merging